export const ADD_LETTUCE = 'ADD_LETTUCE'
export const ADD_BACON = 'ADD_BACON'
export const ADD_CHEESE = 'ADD_CHEESE'
export const ADD_MEAT = 'ADD_MEAT'

export const REMOVE_LETTUCE = 'REMOVE_LETTUCE'
export const REMOVE_BACON = 'REMOVE_BACON'
export const REMOVE_CHEESE = 'REMOVE_CHEESE'
export const REMOVE_MEAT = 'REMOVE_MEAT'
export const REMOVE_ALL = 'REMOVE_ALL'